added style
String-xyz/unity-sdk pull request #7
Opened 2023-03-18 01:53 UTC by saito-sv

2023-03-18 02:35 UTC, Auroter requested changes
I am not seeing any style changes when I call SetStyle.  I added some constructors for the style.  Here is the code I used to try and change the style:

`        // Create a new custom style using the inline Style constructor
        WebEventManager.SetStyle(new (
            baseColor: "black",
            baseSize: "16px",
            autofillColor: "yellow",
            hoverColor: "white",
            focusColor: "green",
            validColor: "red",
            placeholderBaseColor: "ffff",
            placeholderBaseSize: "20px",
            placeholderStateColor: "blue"));`

2023-03-24 02:59 UTC, saito-sv commented on Runtime/WebEventManager.cs
> -            if (!loaded)
since we are no longer initializing the iframe right away, we don't need to wait.

2023-03-28 18:42 UTC, auroter approved these changes
![image](https://user-images.githubusercontent.com/7332587/228336675-c4cb0fe6-3e99-4382-b109-f0e47bd7387d.png)
LGTM

2023-03-29 21:02 UTC, ocasta181 approved these changes

2023-03-29 21:15 UTC, merged